spring.application.name=examapp
# DATABASE CONFIGURATION
spring.datasource.url=jdbc:mysql://metro.proxy.rlwy.net:47012/railway
spring.datasource.username=root
spring.datasource.password=qcrvEGdrPtcHErNHYmvsNbHSoCaYWXIm
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# RENDER PORT
server.port=${PORT:8080}

# JPA SETTINGS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=shaikajith2001@gmail.com
spring.mail.password=qyuxcpkbygjmyfsi

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true